general {
    before_sleep_cmd = playerctl -a pause
    after_sleep_cmd = hyprctl dispatch dpms on
	lock_cmd = playerctl -a pause ; hyprlock
#	unlock_cmd = playerctl -a play
}

listener {
    timeout = 240
    on-timeout = brightnessctl -s set 50%-
    on-resume = brightnessctl -r
}

listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off & loginctl lock-session
    on-resume = hyprctl dispatch dpms on
}

listener {
	timeout = 900
	on-timeout = systemctl hibernate
}
