LAPTOP_WIDTH_PX = 2880
LAPTOP_HEIGHT_PX = 1920
LAPTOP_REFRESH_HZ = 60.0
LAPTOP_SCALE = 1.25
LAPTOP_LOGICAL_WIDTH = LAPTOP_WIDTH_PX / LAPTOP_SCALE
LAPTOP_LOGICAL_HEIGHT = LAPTOP_HEIGHT_PX / LAPTOP_SCALE

EXTERNAL_MONITOR_WIDTH_PX = 1920
EXTERNAL_MONITOR_HEIGHT_PX = 1080
EXTERNAL_MONITOR_REFRESH_HZ = 60.0
EXTERNAL_MONITOR_SCALE = 1

hl.monitor({
    output = MAIN_MONITOR_OUTPUT,
    mode = LAPTOP_WIDTH_PX .. "x" .. LAPTOP_HEIGHT_PX .. "@" .. LAPTOP_REFRESH_HZ,
    position = "0x"..EXTERNAL_MONITOR_HEIGHT_PX / EXTERNAL_MONITOR_SCALE,
    scale = LAPTOP_SCALE,
})
for i=1,4,1 do
	hl.monitor({
		output = "DP-"..i,
		mode = EXTERNAL_MONITOR_WIDTH_PX .. "x" .. EXTERNAL_MONITOR_HEIGHT_PX .. "@" .. EXTERNAL_MONITOR_REFRESH_HZ,
		position = "0x0",
		scale = EXTERNAL_MONITOR_SCALE,
	})
end

for i=1,9,1 do
	hl.workspace_rule({workspace=tostring(i), monitor="eDP-1"})
end

-- monitor=HDMI-A-1, preferred, auto, 1, mirror, eDP-1
