hl.on("hyprland.start", function()
    -- hl.exec_cmd("\"sudo systemctl start iwd\"")
    -- hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("\"systemctl enable --now auto-cpufreq\"")
    -- hl.exec_cmd("\"battery_monitor.sh\"")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("dbus-update-activation-environment --systemd GNOME_KEYRING_CONTROL")
    hl.exec_cmd("noctalia")
	hl.exec_cmd("hyprpm reload")
	hl.exec_cmd("flatpak run --system com.dec05eba.gpu_screen_recorder")
	hl.exec_cmd("kdeconnectd")
	hl.exec_cmd("sleep 2 && " .. ipc .. "bar-hide side")
	hl.exec_cmd("systemctl enable kanata")
end)
